version: 0.1

eb_codebuild_settings:
  CodeBuildServiceRole: role-name
  ComputeType: size
  Image: image
  Timeout: minutes

phases:
	install:
		commands:
			- ./install-client
	pre_build:
		commands:
			- echo Nothing to do in the pre_build phase...
	build:
		commands:
			- echo Build started on `date`
			- ./build-client
	post_build:
		commands:
			- echo Build completed on `date`
artifacts:
	files:
		- **/*
	discard-paths: no
