version: 0.1

environment_variables:
  plaintext:
    NODE_ENV: "production4"

phases:
  install:
    commands:
      - ./install-client
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./build-client
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - **/*
  discard-paths: no
