version: 0.1

eb_codebuild_settings:
  CodeBuildServiceRole: aws-elasticbeanstalk-ec2-role
  ComputeType: t2.micro
  Image: aws/codebuild/eb-nodejs-4.4.6-amazonlinux-64:2.1.3
  Timeout: 7

environment_variables:
  plaintext:
    NODE_ENV: "production"

phases:
	install:
		commands:
			- ./install-client
	pre_build:
		commands:
			- echo Nothing to do in the pre_build phase...
	build:
		commands:
			- echo Build started on `date`
			- ./build-client
	post_build:
		commands:
			- echo Build completed on `date`
artifacts:
	files:
		- **/*
	discard-paths: no
